// Атлас ударов — события. Разметка ручная по открытым источникам (сводка 4.09–5.10.2026).
// approx:true — метка указывает зону ~2 км, а не точку. Версии сторон — заявления, не подтверждённые факты.
// Теги: UA=официально-UA, RU=официально-RU, OSINT, SOC=соцсети. links — публикации-источники.
const EVENTS = [
{date:"2026-09-04",title:"Штаб СБУ, центр Киева",type:"gov",lat:50.4474,lng:30.5128,approx:true,means:"одиночный БПЛА",ua:"По словам Зеленского, удар был нацелен на кабинет и. о. главы СБУ Александра Поклада.",ru:"",cas:"Киев: 12 раненых",tags:["UA"],links:[{t:"Hromadske (en)",u:"https://hromadske.ua/en/kyyiv/270498-russian-drone-hits-sbu-headquarters-in-central-kyiv-zelenskyy-says"},{t:"Reuters",u:"https://www.thestar.com.my/news/world/2026/09/04/russia-hits-ukraine039s-security-service-headquarters-in-kyiv-zelenskiy-says"}]},
{date:"2026-09-05",title:"Бучанский район: жилой сектор",type:"res",lat:50.5436,lng:30.2120,approx:true,means:"массированная атака: БПЛА и ракеты",ua:"КОВА: 28 повреждённых объектов в пяти районах области.",ru:"",cas:"Область: 2 погибших",tags:["UA"]},
{date:"2026-09-08",title:"Голосеевский район: жилые дома",type:"res",lat:50.3925,lng:30.4895,approx:true,means:"166 «Шахедов» (больше половины реактивные), 32 Х-101, баллистика из Курской обл., «Оникс»",ua:"Люди были заблокированы в квартирах; по Украине сбито 175 целей, попадания на 29 локациях.",ru:"Графика «Targeting day and night» (по ABC).",cas:"Киев: 2 погибших, 10 раненых (ГСЧС); ABC News — не менее 5 погибших",tags:["UA","OSINT"],links:[{t:"ABC News",u:"https://abcnews.com/International/complex-russian-attack-kills-2-kyiv-after-us/story?id=136265522"}]},
{date:"2026-09-08",title:"Соломенский район: жилые дома, пожар в учебном заведении",type:"res",lat:50.4283,lng:30.4480,approx:true,means:"та же атака, что и по Голосеевскому",ua:"Повреждён фасад станции метро; разрушения также в Днепровском и Подольском районах.",ru:"",cas:"учтено в сводке за 8.09",tags:["UA"],links:[{t:"ABC News",u:"https://abcnews.com/International/complex-russian-attack-kills-2-kyiv-after-us/story?id=136265522"}]},
{date:"2026-09-18",title:"Подольский район: нежилое здание",type:"ind",lat:50.4712,lng:30.5055,approx:true,means:"ночью БПЛА, днём баллистика",ua:"Кличко: «Киев под обстрелом баллистикой».",ru:"",cas:"Киев: 1 раненый; область: 3 раненых детей (акубаротравмы)",tags:["UA"]},
{date:"2026-09-24",title:"Оболонь: уничтожено не менее 16 гаражей",type:"res",lat:50.5075,lng:30.4980,approx:true,means:"282 БПЛА, «Циркон», Искандер-М, С-400, KN-23 — три волны баллистики",ua:"По Украине сбито 227 целей; по Киеву, по Зеленскому, сбито 60% баллистики. Обезврежена боевая часть ~230 кг.",ru:"",cas:"Киев: 2 погибших, 8 раненых (Кличко/ГСЧС)",tags:["UA"],links:[{t:"Укр. правда (en)",u:"https://www.pravda.com.ua/eng/news/2026/09/24/8054830/"},{t:"my.ua",u:"https://my.ua/news/cluster/2026-09-24-est-pogibshie-pod-zavalami-mogut-byt-liudi-chto-izvestno-o-posledstviiakh-ataki-rf-na-kiev"},{t:"ТСН",u:"https://kyiv.tsn.ua/ru/kyiv/krovavyy-raketnyy-udar-po-kievu-kolichestvo-zhertv-rastet-poslednie-dannye-vse-podrobnosti-ob-atake-obnovleno-3159656.html"}]},
{date:"2026-09-24",title:"Соломенский район: цех Dukachi, пожары",type:"ind",lat:50.4300,lng:30.4550,approx:true,means:"та же атака",ua:"Пожары и разрушения также в Подольском и Днепровском районах.",ru:"",cas:"",tags:["UA"],links:[{t:"ТСН",u:"https://kyiv.tsn.ua/ru/kyiv/krovavyy-raketnyy-udar-po-kievu-kolichestvo-zhertv-rastet-poslednie-dannye-vse-podrobnosti-ob-atake-obnovleno-3159656.html"}]},
{date:"2026-09-25",title:"Высший совет правосудия",type:"gov",lat:50.4512,lng:30.4662,approx:true,means:"ночью 295 БПЛА по Украине; днём реактивные «Шахеды» по Киеву",ua:"Повреждено здание ВСП, работа органа приостановлена, 6 пострадавших.",ru:"",cas:"Киев за сутки: 4–5 погибших, к вечеру 59 раненых",tags:["UA"],links:[{t:"НВ",u:"https://nv.ua/ukraine/events/rankoviy-udar-bpla-u-kiyevi-poshkodzheno-budivlyu-vishchoji-radi-pravosuddya-jiji-robotu-zupineno-ye-poraneni-50644529.html"},{t:"my.ua",u:"https://my.ua/news/cluster/2026-09-25-udar-po-vishchii-radi-pravosuddia-u-kiievi-shestero-postrazhdalikh-organ-prizupiniv-robotu/5a26053e-0f11-a8d3-318f-7f4cce025853"}]},
{date:"2026-09-25",title:"Печерск: 16-этажный дом, этажи 7–10",type:"res",lat:50.4270,lng:30.5440,approx:true,means:"реактивный БПЛА",ua:"",ru:"",cas:"Погиб 14-летний подросток",tags:["UA"],links:[{t:"Слово і діло (25.09)",u:"https://ru.slovoidilo.ua/2026/09/25/novost/obshhestvo/okkupanty-udarili-parkovke-kieve-est-pogibshie-i-postradavshie"}]},
{date:"2026-09-25",title:"Борисполь: «место сборки БПЛА» — версия РФ",type:"ind",lat:50.3500,lng:30.9550,approx:true,means:"",ua:"Украинской стороной не комментировалось.",ru:"Поражено место сборки и хранения БПЛА с двигателями Honeywell TFE731 для ракет «Фламинго».",cas:"",tags:["RU"]},
{date:"2026-09-26",title:"Фармзавод «Дарница» — повторный удар",type:"ind",lat:50.4037,lng:30.6540,approx:true,means:"БПЛА",ua:"ТСН: горел жилой дом в Соломенском районе.",ru:"",cas:"Киев: «есть погибшие», много раненых, в т.ч. ребёнок — точных цифр нет",tags:["UA"],links:[{t:"ТСН",u:"https://kyiv.tsn.ua/ru/kyiv/rossiya-dalshe-atakuet-kiev-zagorelsya-zhiloy-dom-est-postradavshie-vse-detali-obnovleno-3175961.html"}]},
{date:"2026-09-27",title:"Подольский район: 16-этажка, 7-й этаж",type:"res",lat:50.4860,lng:30.4450,approx:true,means:"БПЛА вечером",ua:"",ru:"",cas:"Киев: 9 раненых",tags:["UA"]},
{date:"2026-09-27",title:"Рынок «Столичный», Софиевская Борщаговка",type:"oth",lat:50.3980,lng:30.3450,approx:true,means:"БПЛА, ночь на 27.09",ua:"Удар по территории рынка (и. о. главы сельсовета). В тот же день, по Зеленскому, уничтожен склад Kärcher и повреждена резиденция посла Саудовской Аравии.",ru:"",cas:"2 погибших; всего по городу за 27.09 — 9 пострадавших",tags:["UA"],links:[{t:"UNN (en)",u:"https://unn.ua/en/amp/a-russian-strike-on-the-stolychnyi-market-in-kyiv-claimed-the-lives-of-two-people"},{t:"LB.ua — итоги 27.09",u:"https://lb.ua/society/2026/09/27/769418_golovne_nedilyu_27_veresnya.html"}]},
{date:"2026-09-27",title:"БЦ Incom: дата-центр Datagroup; рядом склад McDonald's",type:"ind",lat:50.4400,lng:30.4800,approx:true,means:"БПЛА",ua:"Бескрестнов. По Минцифры, после удара 23.09 без интернета оставались ~100 000 домохозяйств.",ru:"",cas:"",tags:["UA","SOC"]},
{date:"2026-09-28",title:"Президиум НАН Украины, ул. Владимирская",type:"gov",lat:50.4441,lng:30.5117,approx:false,means:"реактивный БПЛА; есть видео прямого попадания",ua:"Зданию около 170 лет, разрушены два этажа.",ru:"Официального комментария не найдено.",cas:"2 погибших сотрудника НАН; по городу за день: 1–2 погибших, 24–26 раненых, среди них 3 ребёнка",tags:["UA","SOC"],links:[{t:"Liga (en)",u:"https://news.liga.net/en/war/news/strike-on-nas-building-in-kyiv-two-academicians-killed"},{t:"Euronews",u:"https://www.euronews.com/2026/09/28/russia-strikes-ukraines-national-academy-of-sciences-killing-at-least-one-person"},{t:"United24",u:"https://united24media.com/war-in-ukraine/two-scientists-killed-in-russian-strike-on-ukraines-national-academy-of-sciences-22926"}]},
{date:"2026-09-28",title:"Медцентр «Добробут»",type:"oth",lat:50.4450,lng:30.4980,approx:true,means:"БПЛА; в тот же день — фармкомпания и АЗС",ua:"",ru:"",cas:"7 раненых",tags:["UA"],links:[{t:"Обозреватель (28.09)",u:"https://www.obozrevatel.com/section-zhizn-stolitsyi/news-rosiya-atakuvala-kyyiv-poshkodzheno-azs-i-budynok-stalas-pozhezha-ye-postrazhdali-foto-28-09-2026.html"}]},
{date:"2026-09-30",title:"ТЭЦ-5, Голосеевский район",type:"enr",lat:50.3872,lng:30.5510,approx:false,means:"«Циркон»/«Оникс», Искандер-М/С-400, 188 БПЛА ночью + 285 днём; впервые реактивный БПЛА с кумулятивно-режущим зарядом (КРСН) против опор ЛЭП",ua:"Экстренные отключения света в Киеве и трёх областях; местами пропадала вода.",ru:"ТЭЦ-5 отдельно не называлась.",cas:"Киев: 2–4 погибших, 5 раненых (по разным источникам)",tags:["UA","OSINT"],osint:"Очаги пожаров — NASA FIRMS",links:[{t:"my.ua — энергетик об ударах по ТЭЦ-5",u:"https://my.ua/news/cluster/2026-10-01-rf-pytaetsia-obestochit-levoberezhnyi-kiev-energetik-rasskazal-ob-udarakh-po-tets-5"},{t:"Forbes.ua",u:"https://forbes.ua/ru/news/u-kijevi-ta-oblasti-zastosuvali-ekstreni-vidkliucennia-svitla-30092026-42532"}]},
{date:"2026-09-30",title:"Трипольская ТЭС, Украинка",type:"enr",lat:50.1313,lng:30.7463,approx:false,means:"та же атака",ua:"Повреждена (NV, Обозреватель).",ru:"Поражена: «питала военное производство юга области».",cas:"",tags:["UA","RU","OSINT"],osint:"Очаги пожаров — NASA FIRMS",links:[{t:"Обозреватель",u:"https://www.obozrevatel.com/section-ekonomika-glavnaya/communalka/news-rosiya-zavdala-naymasovanishoho-udaru-po-enerhetytsi-ukrayiny-z-2025-roku-poshkodzheno-trypilsku-tes-30-09-2026.html"},{t:"Meduza",u:"https://meduza.io/news/2026/09/30/rossiyskie-voyska-nanesli-udary-po-kievu-i-kievskoy-oblasti-pogibli-tri-cheloveka-semero-raneny"},{t:"БФМ — сводка МО РФ",u:"https://www.bfm.ru/news/619403"}]},
{date:"2026-09-30",title:"Подстанция 750 кВ «Киевская», с. Наливайковка — версия РФ",type:"enr",lat:50.4310,lng:29.9520,approx:true,means:"",ua:"Официально не называлась.",ru:"Поражена 30.09 — по МО, обеспечивала переток электроэнергии (в т.ч. с Ровенской АЭС) для ВПК Киева и области; повторный удар 2.10.",cas:"",tags:["RU"],links:[{t:"БФМ — сводка МО РФ",u:"https://www.bfm.ru/news/619403"},{t:"Коммерсантъ",u:"https://www.kommersant.ru/doc/8991884"}]},
{date:"2026-09-30",title:"Киевская ГЭС, Вышгород — версия РФ",type:"enr",lat:50.5885,lng:30.4590,approx:false,means:"",ua:"Не подтверждено.",ru:"Поражена; по росСМИ с фото МО — повреждены проезжая часть дамбы и машинный зал.",cas:"",tags:["RU"],links:[{t:"БФМ — сводка МО РФ",u:"https://www.bfm.ru/news/619403"},{t:"Вечерняя Москва",u:"https://vm.ru/news/1160871-kievskaya-ges-poluchila-sereznye-povrezhdeniya-v-rezultate-ataki-vs-rf"}]},
{date:"2026-09-30",title:"Вышгород: разрушен жилой дом",type:"res",lat:50.5840,lng:30.4890,approx:true,means:"баллистика и БПЛА в ночь на 30.09",ua:"Из-под завалов спасли троих; в Киеве той же ночью погибли две женщины.",ru:"",cas:"Погиб ребёнок, 3 раненых",tags:["UA"],links:[{t:"Вікна",u:"https://vikna.tv/dlia-tebe/vijna-v-ukrayini/obstrily-kyyeva-sogodni-30-veresnya-2026-shho-vidomo/"},{t:"Zaxid.net",u:"https://zaxid.net/rosiyani_vnochi_masovano_atakuvali_kiyiv_ta_oblast_n1646827"}]},
{date:"2026-09-30",title:"Горенычи: аккумуляторный парк — версия РФ",type:"enr",lat:50.4590,lng:30.2510,approx:true,means:"",ua:"",ru:"Поражён.",cas:"",tags:["RU"]},
{date:"2026-09-30",title:"ЦОД De Novo — версия РФ",type:"ind",lat:50.4500,lng:30.5200,approx:true,means:"",ua:"",ru:"По МО — «коммуникационный центр», поражён ЦОД «Де Ново»: «обмен интернет-трафиком для армии».",cas:"",tags:["RU"],links:[{t:"RTVI — сводка МО РФ",u:"https://rtvi.com/news/rossijskie-sily-nanesli-massirovannyj-udar-po-energoobektam-ukrainy/"},{t:"БФМ",u:"https://www.bfm.ru/news/619403"}]},
{date:"2026-10-01",title:"Южный мост: 3–5 попаданий за 1–2.10",type:"brg",lat:50.3927,lng:30.5892,approx:false,means:"реактивные БПЛА; предположительно «Герань» с кумулятивно-режущей БЧ [неверифицировано]",ua:"Мост закрыт полностью; метро по нему — только после экспертизы. По УП, один дрон взорвался у опоры при идущем поезде метро. Со 2.10 ограничено движение по мостам Метро и Патона.",ru:"«Автожелезнодорожный мост, обеспечивавший переброску войск и грузов в Донбасс».",cas:"",tags:["UA","RU"],links:[{t:"УНИАН — дрон при идущем поезде",u:"https://www.unian.net/economics/transport/udar-po-yuzhnomu-mostu-v-kieve-dron-atakoval-yuzhnyy-most-vo-vremya-dvizheniya-poezda-metro-novosti-kieva-13515480.html"},{t:"Forbes.ua — три моста",u:"https://forbes.ua/ru/news/u-kijevi-obmezili-rux-tryoma-mostami-pivdennii-povnistiu-perekritii-02102026-42588"},{t:"НВ — метро после экспертизы",u:"https://nv.ua/kyiv/dvizhenie-metro-po-yuzhnomu-mostu-vosstanovlenie-posle-udarov-ozhidaet-ekspertizy-50646601.html"}]},
{date:"2026-10-03",title:"Северный мост",type:"brg",lat:50.4905,lng:30.5345,approx:false,means:"БПЛА; ночью по Киеву также баллистика",ua:"Повреждены полотно и контактная сеть троллейбуса; движение частично ограничено. Понтонные переправы — со следующей недели.",ru:"«Мост обеспечивал переброску войск».",cas:"На мосту 2 раненых (BBC); от баллистики по городу 1 погибший, 2 раненых — возможно, те же люди",tags:["UA","RU"],links:[{t:"CNN",u:"https://www.cnn.com/2026/10/03/europe/russia-strikes-northern-southern-bridges-kyiv-attacks-intl"},{t:"Kyiv Independent",u:"https://kyivindependent.com/russia-strikes-key-kyiv-bridge-for-3rd-straight-day-as-attacks-intensify/"},{t:"Meduza (en)",u:"https://meduza.io/en/news/2026/10/03/russian-forces-strike-a-second-major-kyiv-bridge-across-the-dnipro-after-two-days-of-attacks-on-the-south-bridge"},{t:"АиФ — заявление МО РФ",u:"https://aif.ru/society/minoborony-vs-rf-udarili-po-severnomu-mostu-v-kieve"}]},
{date:"2026-10-03",title:"Логистический узел «Гостомель» — версия РФ",type:"ind",lat:50.5850,lng:30.2220,approx:true,means:"",ua:"Bloomberg: удар по логистическому центру под Киевом.",ru:"Поражён. По сводкам МО, Гостомель — повторяющаяся цель: удары по логцентрам заявлялись и 10–11.09 (хранение комплектующих БПЛА).",cas:"",tags:["RU","OSINT"],links:[{t:"RTVI — сводка МО за 11.09",u:"https://rtvi.com/news/minoborony-soobshhilo-ob-udarah-po-voennym-obektam-ukrainy-ot-kieva-do-odessy/"}]},
{date:"2026-10-04",title:"Северный мост: повторное попадание в полотно",type:"brg",lat:50.4905,lng:30.5345,approx:false,means:"обломки/реактивный БпЛА",ua:"Кличко: влучання в дорожнє полотно Північного мосту; двоє постраждалих, одного госпіталізували. Со 2.10 движение по мосту уже было ограничено.",ru:"",cas:"2 раненых на мосту",tags:["UA"],links:[{t:"Кличко (ТГ) 10:34",u:"https://t.me/vitaliy_klitschko/7761"},{t:"Кличко (ТГ) — 2 раненых",u:"https://t.me/vitaliy_klitschko/7765"}]},
{date:"2026-10-04",title:"Левый берег: обломки БпЛА (Днепровский, Дарницкий, Оболонь)",type:"oth",lat:50.4650,lng:30.6100,approx:true,means:"обломки БпЛА; в Оболони — неразорвавшийся боеприпас",ua:"Кличко: обломки на крыше частного дома и у дороги (Днепровский), на припаркованном авто и территории школы (Дарницкий); в Оболонском районе упал БпЛА с недетонировавшим боеприпасом.",ru:"",cas:"без пострадавших",tags:["UA"],links:[{t:"Кличко (ТГ) — Днепровский",u:"https://t.me/vitaliy_klitschko/7760"},{t:"Кличко (ТГ) — Оболонь",u:"https://t.me/vitaliy_klitschko/7766"}]},
{date:"2026-10-04",title:"Деснянский район: повреждена теплотрасса",type:"enr",lat:50.5150,lng:30.6050,approx:true,means:"последствия удара по левобережью",ua:"Кличко: из-за удара повреждена тепломагистраль — в Деснянском районе временно нет горячей воды; ремонтные бригады восстанавливают.",ru:"",cas:"",tags:["UA"],links:[{t:"Кличко (ТГ)",u:"https://t.me/vitaliy_klitschko/7762"}]},
{date:"2026-10-05",title:"Печерский район: горели автомобили во дворе",type:"res",lat:50.4270,lng:30.5440,approx:true,means:"вечерний БпЛА",ua:"ГСЧС: вечером БпЛА атаковал столицу; во дворе многоэтажки загорелись 2 авто, ещё одно повреждено. Погибших и пострадавших нет.",ru:"",cas:"без пострадавших",tags:["UA"],links:[{t:"ГСЧС (ТГ)",u:"https://t.me/dsns_telegram/76676"}]}
];
const PERIOD = {start:"2026-09-04", end:"2026-10-05"};
